### ISSUE TITLE
Github and Twitter icons swapped

### ISSUE THREAD

**Issue by DavidFV2296190** [simeononsecurity/simeononsecurity.ch#642]
**Describe the bug**
The icons for both Github and Twitter are swapped

**To Reproduce**
1. Load the website
2. Scroll at the bottom
3. Check the links

**Expected behavior**
Clicking on Github icon should send the user to Github and clicking the Twitter icon should send the user to Twitter(X)

**Screenshots**
![image](https://github.com/simeononsecurity/simeononsecurity.ch/assets/3428386/378855d7-bb71-47ec-8816-39fe55160423)

**Comment by simeononsecurity** [comment]
Thanks @DavidFV2296190 !
